### ISSUE TITLE
Change Password & Delete Account

### ISSUE THREAD

**Issue by sn0n** [dBuidl/ConfigDN#15]
Currently there are no options to change password or delete account on site when logged in with local username and password.

**Comment by sn0n** [comment]
Failed to authenticate.

could we also get a forgot password option? ^>^

**Comment by cadawg** [comment]
Forgotten password has been added, I'll look at adding the others in the near future

**Comment by cadawg** [comment]
All the requests mentioned here have been added. It'll be live on ConfigDN.com shortly. Thanks for the issue :)
